name: miroiterie_app
description: Application de gestion pour miroiterie/menuiserie
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.12.0
  sqflite: ^2.3.0
  intl: ^0.19.0
  fl_chart: ^0.66.0
  file_picker: ^6.1.1
  syncfusion_flutter_pdfviewer: ^24.1.41
  syncfusion_flutter_pdf: ^24.1.41
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

